apiVersion: v1
kind: Service
metadata:
  name: g05-lab04
  namespace: mzinga-lab4
spec:
  selector:
    app: g05-lab04
    # Added slot label for blue-green deployment
    slot: blue
  ports:
    - port: 80
      targetPort: 8080